### ISSUE TITLE
Would it be possible to support UnRaid?

### ISSUE THREAD

**Issue by Unthred** [ChuckPa/PlexDBRepair#130]
I am running plex using this docker image plexinc/pms-docker on UnRaid server.
Would it be possible to add support for this and if so would you need any info from me?

Thanks

**Comment by Unthred** [comment]
You could add UnRaid to your list of supported hosts.
I put the code as suggested adjacent /config
exec'd into the container stopped plex with ./plex_service.sh -d
then ran you script.

I now realise I probably should have ran it from outside the container but it worked regardless

thanks verrrrry much!

**Comment by ChuckPa** [comment]
OOOOPs.  

Documentation oversight on my part.   

1.  If it ran, then there's no need to add support.    You can't run it outside the container (it doesn't know where things are)
     It shows "Docker" in the menu header for Plex,inc containers.

2.  I'll fix the documentation to show Plex,Inc   PMS Docker.    

3.  I'll also recheck the start-stop control.      If it shows in the menu as available  then you have it.

**Comment by ChuckPa** [comment]
Documentation updated  as requested.

Plex,inc and LSIO images use the standard  "Docker" platform name because they were the first.
Both use the same structure internally.

Independent of the host OS (e.g.  Unraid),  if the container is Plex,Inc or LSIO  then it's  "Docker" platform.

I opted to keep them this way, as "Docker",  and add clarifying documentation

**Comment by Unthred** [comment]
Amazing thanks so much for making a tedious task really easy!
