### ISSUE TITLE
Options to stop and start Plex?

### ISSUE THREAD

**Issue by CLHatch** [ChuckPa/PlexDBRepair#39]
It might be an idea to have options to stop and start Plex from the menu/command-line.  I see in the script that it already has to determine how Plex is installed (LSIO, HOTIO, etc), so could use that information to use the correct stop/start commands.

**Comment by ChuckPa** [comment]
Starting and stopping PMS from within a container is easy because the container is still running.
Doing this on the main host environment (Workstation or NAS)  isn't possible because each platform has different package installation methods (as defined by the vendor/distro).

I had thought of that during initial design.    It spiraled out of scope in complexity so fast that it would have become a maintenance nightmare.
